#!/usr/bin/env bash
# Cursor cloud agent start for Socratic-Trade.
# 1. Load non-secret Infisical selectors from .cursor/infisical.env.
# 2. If INFISICAL_CLIENT_ID + INFISICAL_CLIENT_SECRET are present in the env
#    injected by the Cursor dashboard, log in via the existing in-repo helper
#    scripts/infisical-run.mjs (or the infisical CLI fallback) and write the
#    resolved secrets to $HOME/.cursor-cloud-env/Socratic-Trade.env (mode 0600).
# 3. Optionally write a tiny .source.sh that re-exports those vars for agents
#    that do not invoke infisical-run.
# 4. If credentials are missing, print the missing dashboard secret NAMES and
#    exit 0 so the agent boot still succeeds.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

REPO_NAME="Socratic-Trade"
ENV_DIR="$HOME/.cursor-cloud-env"
ENV_FILE="$ENV_DIR/${REPO_NAME}.env"
SOURCE_FILE="$ENV_DIR/${REPO_NAME}.source.sh"

log()   { printf '[cursor-cloud-start] %s\n' "$*"; }
warn()  { printf '[cursor-cloud-start] WARN: %s\n' "$*" >&2; }
names_only() { printf '%s\n' "$1"; }

mkdir -p "$ENV_DIR"
chmod 700 "$ENV_DIR"

# 1. Load committed selectors (non-secret PROJECT_ID / ENV / DOMAIN).
if [[ -f .cursor/infisical.env ]]; then
  # shellcheck disable=SC1091
  set -a; source .cursor/infisical.env; set +a
  log "Loaded non-secret Infisical selectors from .cursor/infisical.env"
else
  warn ".cursor/infisical.env missing; relying on Cursor dashboard env only."
fi

# 2. Dashboard secrets -- NAMES only, never values.
missing=()
[[ -z "${INFISICAL_CLIENT_ID:-}" ]]     && missing+=("INFISICAL_CLIENT_ID")
[[ -z "${INFISICAL_CLIENT_SECRET:-}" ]] && missing+=("INFISICAL_CLIENT_SECRET")

if (( ${#missing[@]} > 0 )); then
  warn "Missing Cursor dashboard secrets: ${missing[*]}"
  warn "Add these names to the Cursor dashboard (values are never logged)."
  warn "Skipping secret export; agents using infisical-run will see the same miss."
  exit 0
fi

# 3. Fetch secrets.  Prefer the in-repo helper (no value echo, scrubs
#    bootstrap credentials, supports shared project + watch).  Fall back to
#    the infisical CLI if the helper is absent.
fetch_via_helper() {
    node ./scripts/infisical-run.mjs -- \
      node -e "const e=process.env;const out=Object.entries(e).filter(([k])=>!['INFISICAL_CLIENT_ID','INFISICAL_CLIENT_SECRET','INFISICAL_TOKEN','INFISICAL_SHARED_CLIENT_ID','INFISICAL_SHARED_CLIENT_SECRET','INFISICAL_SHARED_TOKEN','PATH','HOME','USER','LOGNAME','SHELL','TMPDIR','TMP','TEMP','LANG','LC_ALL'].includes(k));for(const [k,v] of out)process.stdout.write(k+'='+v+'\n');" \
      > "$ENV_FILE.tmp"
}

fetch_via_cli() {
    local token
    token="$(infisical login --method universal-auth \
      --client-id "$INFISICAL_CLIENT_ID" \
      --client-secret "$INFISICAL_CLIENT_SECRET" \
      --silent --output=plain 2>/dev/null || true)"
    if [[ -z "${token:-}" ]]; then
      warn "infisical CLI login failed; aborting secret export."
      exit 0
    fi
    INFISICAL_TOKEN="$token" \
      infisical export \
        --env="${INFISICAL_ENV:-dev}" \
        --projectId="${INFISICAL_PROJECT_ID}" \
        --plain --output=dotenv \
        > "$ENV_FILE.tmp" 2>/dev/null || true
}

if [[ -f scripts/infisical-run.mjs ]]; then
  if fetch_via_helper; then
    :
  else
    warn "infisical-run.mjs failed; trying infisical CLI fallback."
    fetch_via_cli
  fi
elif command -v infisical >/dev/null 2>&1; then
  fetch_via_cli
else
  warn "Neither scripts/infisical-run.mjs nor infisical CLI found."
  warn "Install Infisical CLI or commit scripts/infisical-run.mjs, then retry."
  exit 0
fi

if [[ ! -s "$ENV_FILE.tmp" ]]; then
  warn "Secret export produced no output; leaving $ENV_FILE untouched."
  rm -f "$ENV_FILE.tmp"
  exit 0
fi

mv "$ENV_FILE.tmp" "$ENV_FILE"
chmod 0600 "$ENV_FILE"

# 4. Companion sourcer (no echo) for agents that bypass infisical-run.
{
  printf '# Auto-generated by scripts/cursor-cloud-start.sh; do not edit.\n'
  printf 'set -a\n'
  printf 'source %q\n' "${ENV_FILE}"
  printf 'set +a\n'
} > "$SOURCE_FILE"
chmod 0600 "$SOURCE_FILE"

log "Wrote $(names_only "$ENV_FILE") and $(names_only "$SOURCE_FILE") (mode 0600)."
log "start complete."